#!/bin/sh

set -o errexit

usage()
{
    cat <<EOF
Usage:
  $0 DIRECTORY TAG
EOF
}

if [ -z "$1" ]; then
    echo "No build target"
    usage_and_exit 1
fi

if [ -z "$2" ]; then
    echo "Missing tag"
    usage_and_exit 1
fi

set -o nounset

if [ ! -e $1 ]; then
    echo "Build target $1 does not exist"
    usage_and_exit 1
fi

if [ ! -e $1/Dockerfile ]; then
    echo "Build target $1 does not include Dockerfile"
    usage_and_exit 1
fi

IMAGE_NAME=$(basename "$1")
TAG=$2

docker tag $IMAGE_NAME abrt/$IMAGE_NAME:$TAG
docker login
docker push abrt/$IMAGE_NAME
