#!/bin/sh

set -o errexit

usage_and_exit()
{
    cat <<EOF
Usage:
  $0 DIRECTORY TAG TAG ...
EOF
    exit $1
}

if [ -z "$1" ]; then
    echo "No build target"
    usage_and_exit 1
fi

if [ $# -lt 2 ]; then
    echo "Missing TAGs"
    usage_and_exit 1
fi

set -o nounset

if [ ! -e $1 ]; then
    echo "Build target $1 does not exist"
    usage_and_exit 1
fi

if [ ! -e $1/Dockerfile ]; then
    echo "Build target $1 does not include Dockerfile"
    usage_and_exit 1
fi

IMAGE_NAME=$(basename "$1")
HUB_TARGET="${HUB_NS:-abrt}/${HUB_REPOSITORY:-${IMAGE_NAME}}"

shift
for TAG in $@; do
    sudo docker tag abrt-$IMAGE_NAME $HUB_TARGET:${TAG}
    echo "Pushing: $HUB_TARGET:${TAG}"
done

USER=${HUB_USER:-$(whoami)}
echo "Logging to hub.docker.com as $USER"
echo "Hit any key to continue or Ctrl-C to quit"
read n

sudo docker login -u $USER || exit 1
sudo docker push $HUB_TARGET
