#!/bin/sh

set -o errexit

usage_and_exit()
{
    cat <<EOF
Usage:
  $0 DIRECTORY FLAVOR
EOF
    exit $1
}

if [ -z "$1" ]; then
    echo "No build target"
    usage_and_exit 1
fi

if [ -z "$2" ]; then
    echo "Missing FLAVOR"
    usage_and_exit 1
fi

set -o nounset

if [ ! -e $1 ]; then
    echo "Build target $1 does not exist"
    usage_and_exit 1
fi

if [ ! -e $1/Dockerfile ]; then
    echo "Build target $1 does not include Dockerfile"
    usage_and_exit 1
fi

NAME=$(basename "$1")
TAG="$NAME-$2"
HUB_USER=${DOCKER_USER:-abrt}

docker tag abrt-$NAME $HUB_USER/abrt:$TAG
docker login
docker push $HUB_USER/abrt
